apiVersion: v1
kind: Namespace
metadata:
  name: vue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: vue
  labels:
        app: vue-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app-container
        image: zakir22/finch-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-app-service
  namespace: vue
spec:
  selector:
    app: vue-app
  ports:
    - port: 8080
      targetPort: 80
