name: Deploy to Kubernetes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  unit_test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci --f
          npm run build
          npm run test
          npm run lint

  deploy:
    needs: unit_test_lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/finch-frontend:latest .
          docker push ${DOCKER_USERNAME}/finch-frontend:latest
      - name: Login to GitHub Packages
        uses: actions/checkout@v3
        with:
          repository: Zakir1109022/finch-frontend
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}